input = '''XHM:PRC,HRP,GTL
CFK:JPF,JVK,CTN
FCB:FCB,CSP,JVK,TBK,GZF
GJC:RQR,JJW,JJW,CSP,CSH
JCT:LJJ,BCF,RHM
BCF:LTP,LJJ,HTK,XHM,XLL
MPP:MKK,SQV,BSQ,KGG,WHH
RSQ:GTL,JVK,HLX,NKF,TVQ
DRK:KNC,FCB,LTP,KGG,DDT
KGG:KJL,CBR,BJM
CJZ:LTP,SKH,HTF
CTN:SCQ,LCP,BJM,TBK,CDJ
LTP:CJZ,FCB,CJZ
DHS:KZL,RQR,MPP,WWV,WHH
CWM:CSH,GPT,BTW
KJL:WWX,CTN,SKH,WHH,SBS
HTK:LJJ,BCF,RNF
NWC:PFT,KFF,RSR
LCK:GPJ,RNF,DDT,CWM,KGG
LCP:GPT,GVG,TBK,NWC,SKH
RNF:HMZ,GPV,SCG,DHS,GTL
KNC:RSR,TBK,XLL,SBS,GPT
BXP:GVG,PRC,LCK,BTW,KJL
HRP:KJL,ZMX,HTF
VRT:SBS,ZBG,BSQ,HTK,JVK
JXZ:DRK,NKF,SQV
LLS:JQF,DDT,WXJ
JQF:BFV,PRC,PCK
WMT:RSR,CBW,MKK
BFB:BBH,JQF,NKF
ZWP:NWC,GVG,PFT,ZQS,ZTL
SDZ:HTF,PFB,BSQ
TBC:SCG,CSP,PRC
CSP:WLW,RHM,HLX,BFV,QRZ
ZQS:RQR,MKK,MKK,CDJ,RSR
WWV:BJM,DRK,CFK,WLW,KNC
PCK:ZTL,HRP,SVF,HLX,FCB
JPF:QSF,ZTL,LTP,GVG,HLX
SCG:RQR,TBC,PFB
KFF:SQV,JXZ,KNC
PRC:WLW,KCL,LLS,TBC,TBK
GPV:JXZ,BFV,BSQ
HMZ:DRK,CSP,QSF,HTV,CBW
NKF:DDT,BXP,KGH,QSF,RSR
RDX:XHM,LTP,LJJ
GZF:ZTL,ZBG,BSQ
KSW:TBC,SCG,MKK
BSQ:LJJ,ZBG,PFB,LCP,DDT
CSH:XHM,MKK,WHH
PFB:ZTL,HTK,HMZ
SQV:BCF,QCK,CSH,HRP,HRP
KZL:VKN,BCF,DDT
MKK:GJC,JVK,CFK,MPP,WMT
WXJ:BXP,MKK,SCG
GPT:BTW,HLX,KZL
XZK:GZH,HLX,QSF,WMT,RHM
WHH:XLL,RNF,CTN,SCQ,BFV
WLW:QLG,SDZ,QRZ
GVG:WLW,CSP,VRT
ZTL:RQR,VKN,ZTL
KCL:BFV,ZMX,HTK,JVK,KFF
TVQ:BXP,RSQ,CWM
QLG:ZTL,GTL,RNF
CBW:SDZ,CJZ,SDZ
XLL:CBR,XHM,SVF,NKF,VRT
SVF:GZH,QRZ,JVK,WXJ,KJL
VKN:SQV,BCF,KZL
CBR:SKH,VRT,CSP,KSW,QSF
BJM:HLX,MPP,CBR,VKN,VKN
ZBG:CJZ,ZTL,GZF,QSF,PFT
LJJ:HRP,BFB,MKK,CFK,GZF
GZH:CJZ,HMZ,SKH,RDX,CTN
RSR:KGH,BFB,CBR
RHM:MPP,GPV,RQR
QSF:DHS,KSW,BTW,CTN,PFT
PFT:LLS,QSF,NKF,WXJ,KGH
HTF:BXP,VKN,HTV,QSF,RQR
TBK:SCG,PCK,NWC
NWR:MKK,KNC,PCK
DDT:PFB,LTP,KCL,BFB,NWR
JJW:PRC,KFF,DRK
QTB:HTF,NWR,HLX
HLX:PRC,QTB,JVK
WWX:ZBG,LJJ,CSP,QTB,SCG
SBS:RSQ,TBC,CFK
GPJ:RSR,LTP,ZQS,KJL,TBC
SCQ:CWM,VRT,SCG
HTV:DHS,TBC,GTL
KGH:KFF,CTN,XZK
BFV:DRK,MPP,RQR,WWX,GZF
ZMX:CTN,QRZ,BJM,TBK,NWC
RQR:SQV,CTN,SBS
BTW:RNF,WWV,GPV
JVK:NWR,HLX,RNF
BBH:ZBG,CJZ,KSW
QRZ:JQF,BCF,HLX,VRT,LCK
CDJ:KSW,PFB,BFV,HTK,QRZ
GTL:SQV,SVF,CSH,SCG,BCF
SKH:JJW,WWV,RNF,VRT,GVG
QCK:HTV,XZK,PFT,BJM,RSR'''

from collections import defaultdict

pop = [line.split(':')[0] for line in input.splitlines()]
newPop = [line.split(':')[1].split(',') for line in input.splitlines()]


countPop = []
for j,s in enumerate(pop):
    population = {s:1}
    count = 0
    for i in range(20):
        newPopulation = defaultdict(int)
        for a,b in population.items():
            for i in newPop[pop.index(a)]:
                newPopulation[i] += b
        population = newPopulation
    countPop.append(sum(population.values()))
    
print(max(countPop)-min(countPop))